{{- if .Values.migrations.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-sspm.migrationsConfigMapName" . }}
  labels:
    {{- include "open-sspm.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- (.Files.Glob "migrations/*.sql").AsConfig | nindent 2 }}
{{- end }}
